global_costmap:
  plugins:
  - {name: static_map_negative, type: "costmap_2d::StaticLayer"}
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: negative_obstacles, type: "costmap_2d::VoxelLayer"}
  - {name: 3d_obstacles, type: "costmap_2d::VoxelLayer"}
  - {name: 2d_obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: pioneer/base_link
  update_frequency: 2.0
  publish_frequency: 0.0
  static_map: 
    map_topic: /projected_map
  static_map_negative: 
    map_topic: /projected_map_negative
    
