local_costmap:
  plugins:
  - {name: obstacles, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacles:
    observation_sources: base_scan
    base_scan: {data_type: PointCloud2, sensor_frame: pioneer/kinect_camera_link, clearing: true, marking: true, topic: /kinect/depth/points}
  global_frame: pioneer/odom
  robot_base_frame: pioneer/base_link
  update_frequency: 5.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.025
