base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  #vel params
  max_vel_x: 1.2
  min_vel_x: -0.1
  max_vel_y: 0  #diff drive
  min_vel_y: 0
  max_rot_vel: 1.5
  min_rot_vel: 0.4
  min_trans_vel: 0.1
  max_trans_vel: 1.2

  #accel params
  acc_lim_x: 2.5
  acc_lim_y: 0  #diff drive
  acc_lim_th: 3

  #forward sim params
  sim_time: 2.0
  vx_samples: 20
  vy_samples: 0 #diff drive
  vth_samples: 40

  #scoring params
  path_distance_bias: 32
  goal_distance_bias: 20
  occdist_scale: 0.02

  #higher goal tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  #lower goal tolerance
  #yaw_goal_tolerance: 0.05
  #xy_goal_tolerance: 0.1
  #latch_xy_goal_tolerance: false
  
  holonomic_robot: false
